name: Build and deploy WAR app to Azure Web App - springboot-specchecker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Azure credentials
      run: |
        echo ${{ secrets.AZURE_CLIENT_ID }} > client_id.txt
        echo ${{ secrets.AZURE_CLIENT_SECRET }} > client_secret.txt
        echo ${{ secrets.AZURE_TENANT_ID }} > tenant_id.txt
        $client_id = Get-Content -Path "client_id.txt"
        $client_secret = Get-Content -Path "client_secret.txt"
        $tenant_id = Get-Content -Path "tenant_id.txt"
        az login --service-principal -u $client_id -p $client_secret -t $tenant_id
    
    - name: Install dependencies
      run: |
        cd ./path/to/your/nodejs/app
        npm ci
    
    - name: Build and deploy
      run: |
        cd ./path/to/your/nodejs/app
        npm run build
        # Add your deployment commands here
        
    - name: Log out from Azure
      run: az logout
